spring:
  application:
    name: prefectj
  profiles:
    active: @profileActive@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/awesome?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      asyncInit: true
      filters: stat
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 5000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
