spring:
  application:
    name: prefectj
  profiles:
    active: @profileActive@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/awesome
    username: root
    password: 123456


management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
