version: '3'
services:
  mysql-service:
    image: mariadb
    ports:
      - "5002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: "Asia/Shanghai"
  redis-service:
    image: redis
    ports:
      - "9736:6379"
  perfectj-service:
    image: openjdk:8-jdk-alpine
    ports:
      - "7070:8080"
    environment:
      TZ: "Asia/Shanghai"
      LOG_FILE: "/log"
    volumes:
      - ../target/perfectj-0.0.1-SNAPSHOT.jar:/app.jar
      - /Users/chenjing/data/prod/perfectj/log:/log
    command: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
